ALTER TABLE planner_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE planner_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE health_daily_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE health_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE challenge_daily_logs ENABLE ROW LEVEL SECURITY;
